name: Deploy Workflow

# TRIGGERS
on:
  push:
    branches:
      # - deploy/*
      - main

# ENVIRONMENT VARIABLES
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  BRANCH_NAME: ${{ github.head_ref || github.ref }}

# CI/CD STEPS
jobs:
  deploy:
    name: Deploy to [www.savedb.site]
    runs-on: ubuntu-latest
    if: always() && !cancelled() && !failure() && contains(github.ref, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy with DXUP
        uses: "digitopvn/diginext-actions@v2"
        with:
          api_key: ${{ secrets.DX_API_KEY }}
          cluster: dxupvn
          registry: digitopdockerhub
          deploy_env: prod
          tail: true
          port: 3000
